### ISSUE TITLE
SlowcontrolElement Print() produces invalid JSON

### ISSUE THREAD

**Issue by robaato** [ToolDAQ/ToolDAQFramework#26]
The JSON format produced by SlowControlElement::Print() is not a valid JSON. 
Notice in the sample below:
```json
[
 {"name":"?","type":"BUTTON"}, 
 {"name":"AdcMask","type":"VARIABLE","max":63,"min":0,"step":1,"value":63}, 
 {"name":"Backend","type":"OPTIONS","options":[PacketMode,Waveforms],"value":""PacketMode""},
 {"name":"Start","type":"BUTTON","value":"1"}, 
 {"name":"Status","type":"INFO","value":"N/A"}, 
 {"name":"Stop","type":"BUTTON","value":"1"}
]
```
the options are not properly quoted and value is double quoted. Both errors prevent front-end usage with JS `JSON.parse`

![obraz](https://github.com/user-attachments/assets/68a0f403-11e0-4240-8745-cc5dc0748e02)

**Comment by brichards64** [comment]
fixed
